"""Market catalog registry - central source of truth for all supported markets."""
from __future__ import annotations

from packages.shared.enums.market import (
    CorrelationCategory, LineUnit, MarketGroup, MarketType,
    OutcomeType, Period, Side,
)
from packages.shared.enums.sport import Sport
from packages.shared.schemas.market import MarketDefinition, MarketOutcome

_OVER_UNDER = [
    MarketOutcome(outcome_type=OutcomeType.OVER, label="Over"),
    MarketOutcome(outcome_type=OutcomeType.UNDER, label="Under"),
]

_HOME_AWAY = [
    MarketOutcome(outcome_type=OutcomeType.HOME, label="Home"),
    MarketOutcome(outcome_type=OutcomeType.AWAY, label="Away"),
]

_HOME_DRAW_AWAY = [
    MarketOutcome(outcome_type=OutcomeType.HOME, label="Home"),
    MarketOutcome(outcome_type=OutcomeType.DRAW, label="Draw"),
    MarketOutcome(outcome_type=OutcomeType.AWAY, label="Away"),
]

_YES_NO = [
    MarketOutcome(outcome_type=OutcomeType.YES, label="Yes"),
    MarketOutcome(outcome_type=OutcomeType.NO, label="No"),
]


def _build_catalog() -> list[MarketDefinition]:
    """Build the complete market catalog across all sports."""
    catalog: list[MarketDefinition] = []

    # ─── SOCCER ────────────────────────────────────────────
    catalog.extend([
        MarketDefinition(
            market_group=MarketGroup.SOCCER_1X2_FT,
            market_type=MarketType.RESULT,
            sport=Sport.SOCCER,
            display_name="1X2 Full Time",
            description="Match result at full time",
            outcomes=_HOME_DRAW_AWAY,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_1x2",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_1X2_HT,
            market_type=MarketType.RESULT,
            sport=Sport.SOCCER,
            display_name="1X2 Half Time",
            supported_periods=[Period.FIRST_HALF],
            outcomes=_HOME_DRAW_AWAY,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_1x2",
        ),
        MarketDefinition(
            market_group=MarketGroup.DOUBLE_CHANCE,
            market_type=MarketType.RESULT,
            sport=Sport.SOCCER,
            display_name="Double Chance",
            outcomes=[
                MarketOutcome(outcome_type=OutcomeType.HOME, label="1X"),
                MarketOutcome(outcome_type=OutcomeType.DRAW, label="12"),
                MarketOutcome(outcome_type=OutcomeType.AWAY, label="X2"),
            ],
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.DRAW_NO_BET,
            market_type=MarketType.RESULT,
            sport=Sport.SOCCER,
            display_name="Draw No Bet",
            outcomes=_HOME_AWAY,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORRECT_SCORE,
            market_type=MarketType.CORRECT_SCORE,
            sport=Sport.SOCCER,
            display_name="Correct Score",
            outcomes=[MarketOutcome(outcome_type=OutcomeType.EXACT_SCORE, label="Exact Score")],
            correlation_categories=[CorrelationCategory.GAME_TOTAL],
            model_family="poisson_score_matrix",
        ),
        MarketDefinition(
            market_group=MarketGroup.WINNING_MARGIN,
            market_type=MarketType.WINNING_MARGIN,
            sport=Sport.SOCCER,
            display_name="Winning Margin",
            outcomes=[MarketOutcome(outcome_type=OutcomeType.BUCKET, label="Margin Bucket")],
            model_family="poisson_derived",
        ),
        # Goals totals
        MarketDefinition(
            market_group=MarketGroup.TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Goals Over/Under",
            line_unit=LineUnit.GOALS,
            default_lines=[0.5, 1.5, 2.5, 3.5, 4.5, 5.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_TOTAL],
            model_family="poisson_totals",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_BTTS,
            market_type=MarketType.YES_NO,
            sport=Sport.SOCCER,
            display_name="Both Teams to Score",
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK, CorrelationCategory.SAME_TEAM_DEFENSE],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_BTTS_OU,
            market_type=MarketType.YES_NO,
            sport=Sport.SOCCER,
            display_name="BTTS & Over/Under",
            line_unit=LineUnit.GOALS,
            default_lines=[2.5, 3.5],
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.GAME_TOTAL],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.TEAM_TOTALS,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.SOCCER,
            display_name="Team Total Goals",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.GOALS,
            default_lines=[0.5, 1.5, 2.5, 3.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CLEAN_SHEET,
            market_type=MarketType.YES_NO,
            sport=Sport.SOCCER,
            display_name="Clean Sheet",
            supported_sides=[Side.HOME, Side.AWAY],
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.SAME_TEAM_DEFENSE],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_WIN_TO_NIL,
            market_type=MarketType.YES_NO,
            sport=Sport.SOCCER,
            display_name="Win to Nil",
            supported_sides=[Side.HOME, Side.AWAY],
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK, CorrelationCategory.SAME_TEAM_DEFENSE],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_EXACT_GOALS,
            market_type=MarketType.CORRECT_SCORE,
            sport=Sport.SOCCER,
            display_name="Exact Team Goals",
            supported_sides=[Side.HOME, Side.AWAY],
            outcomes=[MarketOutcome(outcome_type=OutcomeType.BUCKET, label="Exact")],
            model_family="poisson_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_FIRST_GOAL_TIME,
            market_type=MarketType.RACE_TO,
            sport=Sport.SOCCER,
            display_name="Time of First Goal",
            outcomes=[MarketOutcome(outcome_type=OutcomeType.BUCKET, label="Time Bucket")],
            model_family="poisson_time",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_TEAM_SCORE,
            market_type=MarketType.YES_NO,
            sport=Sport.SOCCER,
            display_name="Team to Score",
            supported_sides=[Side.HOME, Side.AWAY],
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_derived",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_FIRST_TEAM_SCORE,
            market_type=MarketType.RESULT,
            sport=Sport.SOCCER,
            display_name="First Team to Score",
            outcomes=_HOME_AWAY,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_derived",
        ),
        # Corners
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_TOTAL,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Corners Over/Under",
            line_unit=LineUnit.CORNERS,
            default_lines=[7.5, 8.5, 9.5, 10.5, 11.5, 12.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_corners",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_TEAM,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.SOCCER,
            display_name="Team Corners Over/Under",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.CORNERS,
            default_lines=[3.5, 4.5, 5.5, 6.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_corners_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_HANDICAP,
            market_type=MarketType.HANDICAP,
            sport=Sport.SOCCER,
            display_name="Corner Handicap",
            line_unit=LineUnit.CORNERS,
            default_lines=[-2.5, -1.5, -0.5, 0.5, 1.5, 2.5],
            outcomes=_HOME_AWAY,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_corners",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_1H,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="1st Half Corners O/U",
            supported_periods=[Period.FIRST_HALF],
            line_unit=LineUnit.CORNERS,
            default_lines=[3.5, 4.5, 5.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_corners",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_RACE,
            market_type=MarketType.RACE_TO,
            sport=Sport.SOCCER,
            display_name="Race to N Corners",
            line_unit=LineUnit.CORNERS,
            default_lines=[3, 5, 7, 9],
            outcomes=[
                MarketOutcome(outcome_type=OutcomeType.HOME, label="Home"),
                MarketOutcome(outcome_type=OutcomeType.AWAY, label="Away"),
                MarketOutcome(outcome_type=OutcomeType.NO, label="Neither"),
            ],
            model_family="poisson_corners_race",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_MOST,
            market_type=MarketType.RESULT,
            sport=Sport.SOCCER,
            display_name="Most Corners",
            outcomes=_HOME_DRAW_AWAY,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_corners",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CORNERS_EXACT,
            market_type=MarketType.CORRECT_SCORE,
            sport=Sport.SOCCER,
            display_name="Exact Total Corners",
            line_unit=LineUnit.CORNERS,
            outcomes=[MarketOutcome(outcome_type=OutcomeType.BUCKET, label="Exact Corners")],
            model_family="poisson_corners",
        ),
        # Cards
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CARDS_TOTAL,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Cards Over/Under",
            description="Yellow = 1pt, Red = 2pts (2nd yellow counts as 1 yellow + 1 red = 3pts total)",
            line_unit=LineUnit.CARDS,
            default_lines=[2.5, 3.5, 4.5, 5.5, 6.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_cards",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CARDS_TEAM,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.SOCCER,
            display_name="Team Cards Over/Under",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.CARDS,
            default_lines=[1.5, 2.5, 3.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SAME_TEAM_DEFENSE],
            model_family="poisson_cards_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CARDS_PLAYER,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.SOCCER,
            display_name="Player to be Booked",
            requires_player=True,
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="logistic_player_card",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_RED_CARD,
            market_type=MarketType.YES_NO,
            sport=Sport.SOCCER,
            display_name="Red Card in Match",
            outcomes=_YES_NO,
            model_family="poisson_cards",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_CARDS_HANDICAP,
            market_type=MarketType.HANDICAP,
            sport=Sport.SOCCER,
            display_name="Cards Handicap",
            line_unit=LineUnit.CARDS,
            default_lines=[-1.5, -0.5, 0.5, 1.5],
            outcomes=_HOME_AWAY,
            model_family="poisson_cards",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_FOULS_TOTAL,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Fouls Over/Under",
            line_unit=LineUnit.FOULS,
            default_lines=[19.5, 21.5, 23.5, 25.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_fouls",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_OFFSIDES_TOTAL,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Offsides Over/Under",
            line_unit=LineUnit.OFFSIDES,
            default_lines=[2.5, 3.5, 4.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_offsides",
        ),
        # Shots
        MarketDefinition(
            market_group=MarketGroup.SOCCER_SHOTS_TOTAL,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Shots Over/Under",
            line_unit=LineUnit.SHOTS,
            default_lines=[19.5, 21.5, 23.5, 25.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_shots",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_SOT_TOTAL,
            market_type=MarketType.TOTALS,
            sport=Sport.SOCCER,
            display_name="Total Shots on Target Over/Under",
            line_unit=LineUnit.SHOTS_ON_TARGET,
            default_lines=[7.5, 8.5, 9.5, 10.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_PACE],
            model_family="poisson_sot",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_SHOTS_TEAM,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.SOCCER,
            display_name="Team Shots Over/Under",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.SHOTS,
            default_lines=[9.5, 11.5, 13.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_shots_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_SOT_TEAM,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.SOCCER,
            display_name="Team Shots on Target Over/Under",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.SHOTS_ON_TARGET,
            default_lines=[3.5, 4.5, 5.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="poisson_sot_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_SOT_PLAYER,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.SOCCER,
            display_name="Player Shots on Target Over/Under",
            requires_player=True,
            line_unit=LineUnit.SHOTS_ON_TARGET,
            default_lines=[0.5, 1.5, 2.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_SCORING],
            model_family="poisson_player_sot",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_PLAYER_SOT_THRESHOLD,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.SOCCER,
            display_name="Player 1+ / 2+ Shots on Target",
            requires_player=True,
            line_unit=LineUnit.SHOTS_ON_TARGET,
            default_lines=[0.5, 1.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_SCORING],
            model_family="poisson_player_sot",
        ),
        # Player scoring
        MarketDefinition(
            market_group=MarketGroup.SOCCER_ANYTIME_SCORER,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.SOCCER,
            display_name="Anytime Goalscorer",
            requires_player=True,
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.PLAYER_SCORING],
            model_family="poisson_player_goals",
        ),
        MarketDefinition(
            market_group=MarketGroup.SOCCER_FIRST_SCORER,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.SOCCER,
            display_name="First / Last Goalscorer",
            requires_player=True,
            outcomes=[MarketOutcome(outcome_type=OutcomeType.PLAYER, label="Player")],
            correlation_categories=[CorrelationCategory.PLAYER_SCORING],
            model_family="poisson_player_goals",
        ),
        # Spread
        MarketDefinition(
            market_group=MarketGroup.SPREAD,
            market_type=MarketType.HANDICAP,
            sport=Sport.SOCCER,
            display_name="Asian Handicap",
            line_unit=LineUnit.GOALS,
            default_lines=[-2.5, -1.5, -0.5, 0.5, 1.5, 2.5],
            outcomes=_HOME_AWAY,
            correlation_categories=[CorrelationCategory.GAME_TOTAL],
            model_family="poisson_spread",
        ),
    ])

    # ─── NBA ───────────────────────────────────────────────
    catalog.extend([
        MarketDefinition(
            market_group=MarketGroup.NBA_MONEYLINE,
            market_type=MarketType.RESULT,
            sport=Sport.NBA,
            display_name="Moneyline",
            outcomes=_HOME_AWAY,
            model_family="xgboost_winner",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_SPREAD,
            market_type=MarketType.HANDICAP,
            sport=Sport.NBA,
            display_name="Point Spread",
            line_unit=LineUnit.POINTS,
            default_lines=[-12.5, -9.5, -7.5, -5.5, -3.5, -1.5, 1.5, 3.5, 5.5, 7.5, 9.5, 12.5],
            outcomes=_HOME_AWAY,
            correlation_categories=[CorrelationCategory.GAME_TOTAL],
            model_family="regression_spread",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.NBA,
            display_name="Total Points Over/Under",
            line_unit=LineUnit.POINTS,
            default_lines=[205.5, 210.5, 215.5, 220.5, 225.5, 230.5, 235.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_TOTAL, CorrelationCategory.GAME_PACE],
            model_family="regression_totals",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_TEAM_TOTALS,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.NBA,
            display_name="Team Total Points",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.POINTS,
            default_lines=[100.5, 105.5, 110.5, 115.5, 120.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SAME_TEAM_ATTACK],
            model_family="regression_team_total",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_1H_WINNER,
            market_type=MarketType.RESULT,
            sport=Sport.NBA,
            display_name="1st Half Winner",
            supported_periods=[Period.FIRST_HALF],
            outcomes=_HOME_AWAY,
            model_family="xgboost_winner",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_QUARTER_WINNER,
            market_type=MarketType.RESULT,
            sport=Sport.NBA,
            display_name="Quarter Winner",
            supported_periods=[Period.FIRST_QUARTER, Period.SECOND_QUARTER, Period.THIRD_QUARTER, Period.FOURTH_QUARTER],
            outcomes=_HOME_AWAY,
            model_family="xgboost_winner",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_1Q_TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.NBA,
            display_name="1st Quarter Total",
            supported_periods=[Period.FIRST_QUARTER],
            line_unit=LineUnit.POINTS,
            default_lines=[50.5, 52.5, 54.5, 56.5, 58.5],
            outcomes=_OVER_UNDER,
            model_family="regression_totals",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_1H_TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.NBA,
            display_name="1st Half Total",
            supported_periods=[Period.FIRST_HALF],
            line_unit=LineUnit.POINTS,
            default_lines=[105.5, 108.5, 110.5, 112.5],
            outcomes=_OVER_UNDER,
            model_family="regression_totals",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_RACE_TO,
            market_type=MarketType.RACE_TO,
            sport=Sport.NBA,
            display_name="Race to Points",
            line_unit=LineUnit.POINTS,
            default_lines=[20, 30, 40, 50],
            outcomes=_HOME_AWAY,
            model_family="regression_race",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_WINNING_MARGIN,
            market_type=MarketType.WINNING_MARGIN,
            sport=Sport.NBA,
            display_name="Winning Margin",
            outcomes=[MarketOutcome(outcome_type=OutcomeType.BUCKET, label="Margin Bucket")],
            model_family="regression_margin",
        ),
        # Player props
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_POINTS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Points",
            requires_player=True,
            line_unit=LineUnit.POINTS,
            default_lines=[10.5, 15.5, 20.5, 25.5, 30.5, 35.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_SCORING, CorrelationCategory.PLAYER_USAGE],
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_REBOUNDS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Rebounds",
            requires_player=True,
            line_unit=LineUnit.REBOUNDS,
            default_lines=[3.5, 5.5, 7.5, 9.5, 11.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_ASSISTS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Assists",
            requires_player=True,
            line_unit=LineUnit.ASSISTS,
            default_lines=[2.5, 4.5, 6.5, 8.5, 10.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_THREES,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Threes Made",
            requires_player=True,
            line_unit=LineUnit.THREES,
            default_lines=[1.5, 2.5, 3.5, 4.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_SCORING],
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_STEALS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Steals",
            requires_player=True,
            line_unit=LineUnit.STEALS,
            default_lines=[0.5, 1.5, 2.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_BLOCKS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Blocks",
            requires_player=True,
            line_unit=LineUnit.BLOCKS,
            default_lines=[0.5, 1.5, 2.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_TURNOVERS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Turnovers",
            requires_player=True,
            line_unit=LineUnit.TURNOVERS,
            default_lines=[1.5, 2.5, 3.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_PRA,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Pts+Reb+Ast",
            requires_player=True,
            line_unit=LineUnit.COMBO,
            default_lines=[20.5, 25.5, 30.5, 35.5, 40.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_PR,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Pts+Reb",
            requires_player=True,
            line_unit=LineUnit.COMBO,
            default_lines=[15.5, 20.5, 25.5, 30.5],
            outcomes=_OVER_UNDER,
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_PA,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Pts+Ast",
            requires_player=True,
            line_unit=LineUnit.COMBO,
            default_lines=[15.5, 20.5, 25.5, 30.5],
            outcomes=_OVER_UNDER,
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_RA,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Reb+Ast",
            requires_player=True,
            line_unit=LineUnit.COMBO,
            default_lines=[8.5, 10.5, 12.5, 15.5],
            outcomes=_OVER_UNDER,
            model_family="xgboost_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_DOUBLE_DOUBLE,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Double-Double",
            requires_player=True,
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="logistic_player_dd",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_TRIPLE_DOUBLE,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Triple-Double",
            requires_player=True,
            outcomes=_YES_NO,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="logistic_player_td",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_FIRST_BASKET,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="First Basket Scorer",
            requires_player=True,
            outcomes=[MarketOutcome(outcome_type=OutcomeType.PLAYER, label="Player")],
            model_family="logistic_first_basket",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_PLAYER_MILESTONES,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NBA,
            display_name="Player Scoring Milestone (20+/25+/30+)",
            requires_player=True,
            line_unit=LineUnit.POINTS,
            default_lines=[19.5, 24.5, 29.5],
            outcomes=_OVER_UNDER,
            model_family="xgboost_player_prop",
        ),
        # Team props
        MarketDefinition(
            market_group=MarketGroup.NBA_TEAM_THREES,
            market_type=MarketType.TEAM_PROP,
            sport=Sport.NBA,
            display_name="Team Threes Made O/U",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.THREES,
            default_lines=[10.5, 12.5, 14.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_team_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_TEAM_REBOUNDS,
            market_type=MarketType.TEAM_PROP,
            sport=Sport.NBA,
            display_name="Team Rebounds O/U",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.REBOUNDS,
            default_lines=[40.5, 43.5, 46.5],
            outcomes=_OVER_UNDER,
            model_family="regression_team_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NBA_TEAM_ASSISTS,
            market_type=MarketType.TEAM_PROP,
            sport=Sport.NBA,
            display_name="Team Assists O/U",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.ASSISTS,
            default_lines=[22.5, 24.5, 26.5],
            outcomes=_OVER_UNDER,
            model_family="regression_team_prop",
        ),
    ])

    # ─── NHL ───────────────────────────────────────────────
    catalog.extend([
        MarketDefinition(
            market_group=MarketGroup.NHL_MONEYLINE,
            market_type=MarketType.RESULT,
            sport=Sport.NHL,
            display_name="Moneyline (Incl. OT/SO)",
            outcomes=_HOME_AWAY,
            model_family="xgboost_winner",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_PUCK_LINE,
            market_type=MarketType.HANDICAP,
            sport=Sport.NHL,
            display_name="Puck Line",
            line_unit=LineUnit.GOALS,
            default_lines=[-2.5, -1.5, -0.5, 0.5, 1.5, 2.5],
            outcomes=_HOME_AWAY,
            model_family="poisson_spread",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.NHL,
            display_name="Total Goals Over/Under",
            line_unit=LineUnit.GOALS,
            default_lines=[4.5, 5.5, 6.5, 7.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.GAME_TOTAL],
            model_family="poisson_totals",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_TEAM_TOTALS,
            market_type=MarketType.TEAM_TOTALS,
            sport=Sport.NHL,
            display_name="Team Total Goals",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.GOALS,
            default_lines=[1.5, 2.5, 3.5, 4.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_team",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_PERIOD_WINNER,
            market_type=MarketType.RESULT,
            sport=Sport.NHL,
            display_name="Period Winner",
            supported_periods=[Period.FIRST_PERIOD, Period.SECOND_PERIOD, Period.THIRD_PERIOD],
            outcomes=_HOME_DRAW_AWAY,
            model_family="poisson_1x2",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_PERIOD_TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.NHL,
            display_name="Period Total Goals",
            supported_periods=[Period.FIRST_PERIOD, Period.SECOND_PERIOD, Period.THIRD_PERIOD],
            line_unit=LineUnit.GOALS,
            default_lines=[0.5, 1.5, 2.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_totals",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_REG_TIME,
            market_type=MarketType.RESULT,
            sport=Sport.NHL,
            display_name="Regulation Time Result",
            supported_periods=[Period.REGULATION],
            outcomes=_HOME_DRAW_AWAY,
            model_family="poisson_1x2",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_WINNING_MARGIN,
            market_type=MarketType.WINNING_MARGIN,
            sport=Sport.NHL,
            display_name="Winning Margin",
            outcomes=[MarketOutcome(outcome_type=OutcomeType.BUCKET, label="Margin Bucket")],
            model_family="poisson_margin",
        ),
        # Player props
        MarketDefinition(
            market_group=MarketGroup.NHL_PLAYER_GOALS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NHL,
            display_name="Player Goals",
            requires_player=True,
            line_unit=LineUnit.GOALS,
            default_lines=[0.5, 1.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_PLAYER_ASSISTS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NHL,
            display_name="Player Assists",
            requires_player=True,
            line_unit=LineUnit.ASSISTS,
            default_lines=[0.5, 1.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_PLAYER_POINTS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NHL,
            display_name="Player Points",
            requires_player=True,
            line_unit=LineUnit.POINTS,
            default_lines=[0.5, 1.5, 2.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_PLAYER_SOG,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NHL,
            display_name="Player Shots on Goal",
            requires_player=True,
            line_unit=LineUnit.SHOTS_ON_TARGET,
            default_lines=[1.5, 2.5, 3.5, 4.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.PLAYER_USAGE],
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_GOALIE_SAVES,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NHL,
            display_name="Goalie Saves Over/Under",
            requires_player=True,
            line_unit=LineUnit.SAVES,
            default_lines=[24.5, 27.5, 30.5, 33.5],
            outcomes=_OVER_UNDER,
            model_family="regression_goalie",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_ANYTIME_SCORER,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.NHL,
            display_name="Anytime Goal Scorer",
            requires_player=True,
            outcomes=_YES_NO,
            model_family="poisson_player_prop",
        ),
        # Team props
        MarketDefinition(
            market_group=MarketGroup.NHL_TEAM_SOG,
            market_type=MarketType.TEAM_PROP,
            sport=Sport.NHL,
            display_name="Team Shots on Goal O/U",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.SHOTS_ON_TARGET,
            default_lines=[27.5, 30.5, 33.5],
            outcomes=_OVER_UNDER,
            model_family="regression_team_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.NHL_TEAM_PP_GOALS,
            market_type=MarketType.TEAM_PROP,
            sport=Sport.NHL,
            display_name="Team Powerplay Goals O/U",
            supported_sides=[Side.HOME, Side.AWAY],
            line_unit=LineUnit.GOALS,
            default_lines=[0.5, 1.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_team_prop",
        ),
    ])

    # ─── TENNIS ────────────────────────────────────────────
    catalog.extend([
        MarketDefinition(
            market_group=MarketGroup.TENNIS_WINNER,
            market_type=MarketType.RESULT,
            sport=Sport.TENNIS,
            display_name="Match Winner",
            outcomes=_HOME_AWAY,
            model_family="elo_winner",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_SET_BETTING,
            market_type=MarketType.CORRECT_SCORE,
            sport=Sport.TENNIS,
            display_name="Set Betting (Exact Sets Score)",
            outcomes=[MarketOutcome(outcome_type=OutcomeType.EXACT_SCORE, label="Sets Score")],
            model_family="elo_sets",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_TOTAL_GAMES,
            market_type=MarketType.TOTALS,
            sport=Sport.TENNIS,
            display_name="Total Games Over/Under",
            line_unit=LineUnit.GAMES,
            default_lines=[20.5, 21.5, 22.5, 23.5, 24.5],
            outcomes=_OVER_UNDER,
            correlation_categories=[CorrelationCategory.SET_DYNAMICS],
            model_family="elo_games",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_GAMES_HANDICAP,
            market_type=MarketType.HANDICAP,
            sport=Sport.TENNIS,
            display_name="Games Handicap",
            line_unit=LineUnit.GAMES,
            default_lines=[-6.5, -4.5, -2.5, 2.5, 4.5, 6.5],
            outcomes=_HOME_AWAY,
            model_family="elo_games",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_SET_TOTALS,
            market_type=MarketType.TOTALS,
            sport=Sport.TENNIS,
            display_name="Total Sets Over/Under",
            line_unit=LineUnit.SETS,
            default_lines=[2.5],
            outcomes=_OVER_UNDER,
            model_family="elo_sets",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_FIRST_SET,
            market_type=MarketType.RESULT,
            sport=Sport.TENNIS,
            display_name="First Set Winner",
            supported_periods=[Period.SET_1],
            outcomes=_HOME_AWAY,
            model_family="elo_winner",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_TIEBREAK,
            market_type=MarketType.YES_NO,
            sport=Sport.TENNIS,
            display_name="Tiebreak in Match",
            outcomes=_YES_NO,
            model_family="elo_tiebreak",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_PLAYER_ACES,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.TENNIS,
            display_name="Player Aces Over/Under",
            requires_player=True,
            line_unit=LineUnit.ACES,
            default_lines=[4.5, 6.5, 8.5, 10.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_player_prop",
        ),
        MarketDefinition(
            market_group=MarketGroup.TENNIS_PLAYER_DFS,
            market_type=MarketType.PLAYER_PROP,
            sport=Sport.TENNIS,
            display_name="Player Double Faults Over/Under",
            requires_player=True,
            line_unit=LineUnit.DOUBLE_FAULTS,
            default_lines=[1.5, 2.5, 3.5, 4.5],
            outcomes=_OVER_UNDER,
            model_family="poisson_player_prop",
        ),
    ])

    return catalog


class MarketRegistry:
    """Central registry for all market definitions."""

    def __init__(self) -> None:
        self._catalog: dict[MarketGroup, MarketDefinition] = {}
        self._by_sport: dict[Sport, list[MarketDefinition]] = {}
        self._bookmaker_mappings: list[BookmakerMapping] = []
        self._load_catalog()

    def _load_catalog(self) -> None:
        for defn in _build_catalog():
            self._catalog[defn.market_group] = defn
            self._by_sport.setdefault(defn.sport, []).append(defn)

    def get(self, market_group: MarketGroup) -> MarketDefinition | None:
        return self._catalog.get(market_group)

    def list_all(self) -> list[MarketDefinition]:
        return list(self._catalog.values())

    def list_for_sport(self, sport: Sport) -> list[MarketDefinition]:
        return self._by_sport.get(sport, [])

    def list_market_groups(self, sport: Sport | None = None) -> list[MarketGroup]:
        if sport:
            return [d.market_group for d in self.list_for_sport(sport)]
        return list(self._catalog.keys())

    def add_bookmaker_mapping(self, mapping: BookmakerMapping) -> None:
        self._bookmaker_mappings.append(mapping)

    def resolve_bookmaker_market(
        self, bookmaker: str, bookmaker_market_name: str,
    ) -> MarketDefinition | None:
        for m in self._bookmaker_mappings:
            if m.bookmaker == bookmaker and m.bookmaker_market_name == bookmaker_market_name:
                return self._catalog.get(m.normalized_market_group)
        return None

    @property
    def total_markets(self) -> int:
        return len(self._catalog)


_registry: MarketRegistry | None = None


def get_registry() -> MarketRegistry:
    global _registry
    if _registry is None:
        _registry = MarketRegistry()
    return _registry
